(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
        						 balance)
        (display "insufficient funds")))

	(define (deposit amount)
	  (set! balance (+ balance amount))
		balance)
	(define (dispatch psswd m)
	  (if (eq? psswd password)
	      (cond ((eq? m 'withdraw) withdraw)
	            ((eq? m 'deposit) deposit)
	           	(else (error "unkown request: make-account" m)))
	      (display "incorrect password")))
	dispatch)